# Базовая конфигурация vsftpd
listen=YES
listen_ipv6=NO
anonymous_enable=YES
anon_root=/var/ftp/pub
local_enable=YES
write_enable=NO
anon_upload_enable=NO
anon_mkdir_write_enable=NO
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
seccomp_sandbox=NO

# Пассивный режим
pasv_enable=YES
pasv_promiscuous=YES
port_promiscuous=YES
pasv_min_port=__PASV_PORT__
pasv_max_port=__PASV_PORT__
pasv_address=__HOST_IP__
listen_port=__FTP_PORT__
